[2021-08-04 14:03:55,017] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C 2021-08-04T14:03:44.460692+00:00 [queued]>
[2021-08-04 14:03:55,044] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C 2021-08-04T14:03:44.460692+00:00 [queued]>
[2021-08-04 14:03:55,044] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:03:55,044] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:03:55,044] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:03:55,055] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_C> on 2021-08-04T14:03:44.460692+00:00
[2021-08-04 14:03:55,060] {standard_task_runner.py:52} INFO - Started process 2039 to run task
[2021-08-04 14:03:55,064] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_C', '2021-08-04T14:03:44.460692+00:00', '--job-id', '2479', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpx9l4gcia', '--error-file', '/tmp/tmp7518a12i']
[2021-08-04 14:03:55,065] {standard_task_runner.py:77} INFO - Job 2479: Subtask training_model_C
[2021-08-04 14:03:55,110] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_C 2021-08-04T14:03:44.460692+00:00 [running]> on host 04479ea62028
[2021-08-04 14:03:55,162] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:03:44.460692+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:03:44.460692+00:00
[2021-08-04 14:03:55,163] {python.py:151} INFO - Done. Returned value was: 5
[2021-08-04 14:03:55,189] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_C, execution_date=20210804T140344, start_date=20210804T140355, end_date=20210804T140355
[2021-08-04 14:03:55,222] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:03:55,238] {local_task_job.py:149} INFO - Task exited with return code 0
