[2021-08-04 14:40:48,581] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B 2021-08-04T14:40:37.634907+00:00 [queued]>
[2021-08-04 14:40:48,602] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B 2021-08-04T14:40:37.634907+00:00 [queued]>
[2021-08-04 14:40:48,603] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:40:48,603] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:40:48,603] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:40:48,626] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_B> on 2021-08-04T14:40:37.634907+00:00
[2021-08-04 14:40:48,632] {standard_task_runner.py:52} INFO - Started process 1271 to run task
[2021-08-04 14:40:48,638] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_B', '2021-08-04T14:40:37.634907+00:00', '--job-id', '2874', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpnfsnelhw', '--error-file', '/tmp/tmp9_21bm8k']
[2021-08-04 14:40:48,639] {standard_task_runner.py:77} INFO - Job 2874: Subtask training_model_B
[2021-08-04 14:40:48,711] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_B 2021-08-04T14:40:37.634907+00:00 [running]> on host 04479ea62028
[2021-08-04 14:40:48,781] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:40:37.634907+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:40:37.634907+00:00
[2021-08-04 14:40:48,782] {python.py:151} INFO - Done. Returned value was: 5
[2021-08-04 14:40:48,817] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_B, execution_date=20210804T144037, start_date=20210804T144048, end_date=20210804T144048
[2021-08-04 14:40:48,874] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:40:48,898] {local_task_job.py:149} INFO - Task exited with return code 0
