[2021-08-04 13:29:47,155] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B 2021-08-04T13:29:43.351917+00:00 [queued]>
[2021-08-04 13:29:47,243] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B 2021-08-04T13:29:43.351917+00:00 [queued]>
[2021-08-04 13:29:47,243] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:29:47,244] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:29:47,244] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:29:47,283] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_B> on 2021-08-04T13:29:43.351917+00:00
[2021-08-04 13:29:47,315] {standard_task_runner.py:52} INFO - Started process 10140 to run task
[2021-08-04 13:29:47,415] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_B', '2021-08-04T13:29:43.351917+00:00', '--job-id', '1548', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp_vzrcan0', '--error-file', '/tmp/tmp7t47fgrq']
[2021-08-04 13:29:47,416] {standard_task_runner.py:77} INFO - Job 1548: Subtask training_model_B
[2021-08-04 13:29:47,687] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_B 2021-08-04T13:29:43.351917+00:00 [running]> on host 04479ea62028
[2021-08-04 13:29:48,010] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:29:43.351917+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:29:43.351917+00:00
[2021-08-04 13:29:48,011] {python.py:151} INFO - Done. Returned value was: 3
[2021-08-04 13:29:48,170] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_B, execution_date=20210804T132943, start_date=20210804T132947, end_date=20210804T132948
[2021-08-04 13:29:48,374] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:29:48,431] {local_task_job.py:149} INFO - Task exited with return code 0
