[2021-08-04 13:26:12,703] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T13:26:08.239729+00:00 [queued]>
[2021-08-04 13:26:12,793] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T13:26:08.239729+00:00 [queued]>
[2021-08-04 13:26:12,794] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:26:12,795] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:26:12,795] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:26:12,837] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-08-04T13:26:08.239729+00:00
[2021-08-04 13:26:12,855] {standard_task_runner.py:52} INFO - Started process 8196 to run task
[2021-08-04 13:26:12,929] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_A', '2021-08-04T13:26:08.239729+00:00', '--job-id', '747', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpao7epqcl', '--error-file', '/tmp/tmp5h4w5xxs']
[2021-08-04 13:26:12,930] {standard_task_runner.py:77} INFO - Job 747: Subtask training_model_A
[2021-08-04 13:26:13,398] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_A 2021-08-04T13:26:08.239729+00:00 [running]> on host 04479ea62028
[2021-08-04 13:26:13,759] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:26:08.239729+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:26:08.239729+00:00
[2021-08-04 13:26:13,761] {python.py:151} INFO - Done. Returned value was: 6
[2021-08-04 13:26:13,907] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20210804T132608, start_date=20210804T132612, end_date=20210804T132613
[2021-08-04 13:26:14,195] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:26:14,214] {local_task_job.py:149} INFO - Task exited with return code 0
