[2021-08-04 13:29:22,635] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B 2021-08-04T13:29:16.875678+00:00 [queued]>
[2021-08-04 13:29:22,695] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_B 2021-08-04T13:29:16.875678+00:00 [queued]>
[2021-08-04 13:29:22,695] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:29:22,696] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:29:22,696] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:29:22,727] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_B> on 2021-08-04T13:29:16.875678+00:00
[2021-08-04 13:29:22,733] {standard_task_runner.py:52} INFO - Started process 9911 to run task
[2021-08-04 13:29:22,757] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_B', '2021-08-04T13:29:16.875678+00:00', '--job-id', '1452', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp8ah5fqnn', '--error-file', '/tmp/tmpyxiifwgd']
[2021-08-04 13:29:22,758] {standard_task_runner.py:77} INFO - Job 1452: Subtask training_model_B
[2021-08-04 13:29:22,957] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_B 2021-08-04T13:29:16.875678+00:00 [running]> on host 04479ea62028
[2021-08-04 13:29:23,222] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:29:16.875678+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:29:16.875678+00:00
[2021-08-04 13:29:23,223] {python.py:151} INFO - Done. Returned value was: 5
[2021-08-04 13:29:23,372] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_B, execution_date=20210804T132916, start_date=20210804T132922, end_date=20210804T132923
[2021-08-04 13:29:23,554] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:29:23,611] {local_task_job.py:149} INFO - Task exited with return code 0
