[2021-08-04 13:25:56,251] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.accurate 2021-08-04T13:25:43.516608+00:00 [queued]>
[2021-08-04 13:25:56,289] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.accurate 2021-08-04T13:25:43.516608+00:00 [queued]>
[2021-08-04 13:25:56,290] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:25:56,290] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:25:56,290] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:25:56,313] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): accurate> on 2021-08-04T13:25:43.516608+00:00
[2021-08-04 13:25:56,344] {standard_task_runner.py:52} INFO - Started process 8042 to run task
[2021-08-04 13:25:56,428] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', '2021-08-04T13:25:43.516608+00:00', '--job-id', '686', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpjkq3dcxp', '--error-file', '/tmp/tmp069mk6qw']
[2021-08-04 13:25:56,429] {standard_task_runner.py:77} INFO - Job 686: Subtask accurate
[2021-08-04 13:25:56,750] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.accurate 2021-08-04T13:25:43.516608+00:00 [running]> on host 04479ea62028
[2021-08-04 13:25:57,059] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:25:43.516608+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:25:43.516608+00:00
[2021-08-04 13:25:57,060] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 13:25:57,061] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2021-08-04 13:25:57,097] {subprocess.py:74} INFO - Output:
[2021-08-04 13:25:57,107] {subprocess.py:78} INFO - accurate
[2021-08-04 13:25:57,107] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 13:25:57,302] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20210804T132543, start_date=20210804T132556, end_date=20210804T132557
[2021-08-04 13:25:57,435] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:25:57,505] {local_task_job.py:149} INFO - Task exited with return code 0
