[2021-08-04 13:55:44,959] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T13:55:34.067338+00:00 [queued]>
[2021-08-04 13:55:44,979] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A 2021-08-04T13:55:34.067338+00:00 [queued]>
[2021-08-04 13:55:44,980] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:55:44,980] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:55:44,980] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:55:44,990] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-08-04T13:55:34.067338+00:00
[2021-08-04 13:55:44,994] {standard_task_runner.py:52} INFO - Started process 820 to run task
[2021-08-04 13:55:44,999] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_A', '2021-08-04T13:55:34.067338+00:00', '--job-id', '2236', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpip8wl1_8', '--error-file', '/tmp/tmppek0nr8s']
[2021-08-04 13:55:45,000] {standard_task_runner.py:77} INFO - Job 2236: Subtask training_model_A
[2021-08-04 13:55:45,043] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_A 2021-08-04T13:55:34.067338+00:00 [running]> on host 04479ea62028
[2021-08-04 13:55:45,097] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:55:34.067338+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:55:34.067338+00:00
[2021-08-04 13:55:45,097] {python.py:151} INFO - Done. Returned value was: 1
[2021-08-04 13:55:45,125] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20210804T135534, start_date=20210804T135544, end_date=20210804T135545
[2021-08-04 13:55:45,165] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:55:45,174] {local_task_job.py:149} INFO - Task exited with return code 0
