[2021-08-04 13:30:16,920] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C 2021-08-04T13:30:12.352931+00:00 [queued]>
[2021-08-04 13:30:17,007] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C 2021-08-04T13:30:12.352931+00:00 [queued]>
[2021-08-04 13:30:17,008] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:30:17,008] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 13:30:17,008] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 13:30:17,075] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_C> on 2021-08-04T13:30:12.352931+00:00
[2021-08-04 13:30:17,130] {standard_task_runner.py:52} INFO - Started process 10417 to run task
[2021-08-04 13:30:17,145] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_C', '2021-08-04T13:30:12.352931+00:00', '--job-id', '1661', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpbtmc4d72', '--error-file', '/tmp/tmpo_lntz9o']
[2021-08-04 13:30:17,166] {standard_task_runner.py:77} INFO - Job 1661: Subtask training_model_C
[2021-08-04 13:30:17,512] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_C 2021-08-04T13:30:12.352931+00:00 [running]> on host 04479ea62028
[2021-08-04 13:30:17,822] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T13:30:12.352931+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T13:30:12.352931+00:00
[2021-08-04 13:30:17,822] {python.py:151} INFO - Done. Returned value was: 9
[2021-08-04 13:30:17,959] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_C, execution_date=20210804T133012, start_date=20210804T133016, end_date=20210804T133017
[2021-08-04 13:30:18,180] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 13:30:18,215] {local_task_job.py:149} INFO - Task exited with return code 0
