[2021-08-04 14:49:28,861] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C 2021-08-04T14:49:17.958228+00:00 [queued]>
[2021-08-04 14:49:28,877] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C 2021-08-04T14:49:17.958228+00:00 [queued]>
[2021-08-04 14:49:28,878] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:49:28,878] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:49:28,878] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:49:28,897] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_C> on 2021-08-04T14:49:17.958228+00:00
[2021-08-04 14:49:28,903] {standard_task_runner.py:52} INFO - Started process 2555 to run task
[2021-08-04 14:49:28,908] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_C', '2021-08-04T14:49:17.958228+00:00', '--job-id', '3134', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpzxigqiv7', '--error-file', '/tmp/tmpqishzre6']
[2021-08-04 14:49:28,908] {standard_task_runner.py:77} INFO - Job 3134: Subtask training_model_C
[2021-08-04 14:49:28,956] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.training_model_C 2021-08-04T14:49:17.958228+00:00 [running]> on host 04479ea62028
[2021-08-04 14:49:29,014] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:49:17.958228+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:49:17.958228+00:00
[2021-08-04 14:49:29,015] {python.py:151} INFO - Done. Returned value was: 9
[2021-08-04 14:49:29,042] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_C, execution_date=20210804T144917, start_date=20210804T144928, end_date=20210804T144929
[2021-08-04 14:49:29,076] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:49:29,082] {local_task_job.py:149} INFO - Task exited with return code 0
